server:
  port: 9006

spring:
  application:
    name: payment-provider-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'

