server:
  port: 9527
spring:
  application:
    name: gateway


  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: paymentlb
          uri: lb://payment-provider
          #uri: http://localhost:8001
          predicates:
            - Path=/payment/lb
#            - Cookie=username, hhjj

        - id: paymentget  #路由ID 没有固定规则 但要求唯一
          #uri: http://localhost:8001  #匹配后提供服务的路径
          #使用服务名调用
          uri: lb://payment-provider
          predicates:
            - Path=/payment/**  # 断言，路径相匹配的进行路由
#            - Cookie=username, hhjj





eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
